New summarizer with example
Sparkier/book_summary pull request #41
Opened 2024-05-09 16:49 UTC by js357

2024-05-10 07:46 UTC, ResearchDaniel requested changes
Some minor suggested changes. 
Would need to rebase on master as soon as the pull request #37 has been merged

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        # Clean paragraphs
Would be nice with a comment stating why cleaning is done and what the given characters are in clear text, e.g., \xa0.

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +    print(f"Model max length: {model_max_length}")
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +    print(summarization_model.tokenizer)
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        paragraphs_clean: list = [s.replace("\n", " ") for s in chapter["paragraphs"]]
Why not use characters_to_replace here?

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        print(f"Chapter {ch_num}: ")
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        chapter_text: str = "\n".join(paragraphs_clean)
I think that the paragraph cleaning could be moved to a separate function that returns the cleaned text. That would make this function easier to understand

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        print(f"Chapter text: {chapter_text}")
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        print(f"Chunk summaries: {chunk_summaries}")
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +    chapter_summaries_text = "".join(chapter_summaries)
Not "\n"?

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +    print(f"Book summary: {book_summary_text}")
Remove

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        input_file.stem + "_summ_(" + MODEL_ID.replace("_", "-").replace("/", "_") + ")"
Nit: I think there is a function that makes it a valid file path

2024-05-10 07:46 UTC, ResearchDaniel commented on backend/book_summarizer.py
> +        no_repeat_ngram_size=3,
It would be good with a comment on why these specific settings are used and what effect it would have if they were changed.

2024-05-16 20:17 UTC, ResearchDaniel commented
@js357 Rebased the code on master. Please see if the functionality is equivalent

2024-06-03 07:12 UTC, ResearchDaniel approved these changes

2024-06-06 10:51 UTC, js357 commented on backend/book_summarizer.py
> +        paragraphs_clean: list = [s.replace("\n", " ") for s in chapter["paragraphs"]]
Right. No longer applicable now.

2024-06-06 10:59 UTC, js357 commented on backend/book_summarizer.py
> +        chapter_text: str = "\n".join(paragraphs_clean)
Yes, it's changed to dict.fromkeys by now, but could still be moved in a function.

2024-06-06 11:02 UTC, js357 commented on backend/book_summarizer.py
> +        input_file.stem + "_summ_(" + MODEL_ID.replace("_", "-").replace("/", "_") + ")"
No longer relevant.

2024-06-06 11:24 UTC, js357 commented on backend/book_summarizer.py
> +        no_repeat_ngram_size=3,
https://github.com/pszemraj/textsum/wiki/Inference-&-Parameters

2024-06-06 11:25 UTC, merged